darktable - redhat
alvistack/ansible-role-darktable pull request #1
Opened 2020-08-10 09:17 UTC by mccheng7c

2020-08-11 06:28 UTC, hswong3i commented on vars/centos-8.yml
> +_rpm_repository:
`_rpm_repository` is used for initializing yum repo with upstream provided `repo.rpm`, not for installing the dependency nor package itself :-(

2020-08-11 06:31 UTC, hswong3i requested changes

2020-08-11 06:31 UTC, hswong3i commented on vars/centos-8.yml
> +_rpm_repository:
`_rpm_repository` is used for initializing yum repo with upstream provided `repo.rpm`, not for installing the dependency nor package itself :-(

Read https://www.darktable.org/install/#rhel and https://www.darktable.org/install/#3rdparty

2020-08-12 06:53 UTC, hswong3i commented on vars/centos-8.yml
> +_rpm_repository:
Required pacakge:
- https://centos.pkgs.org/8/centos-powertools-x86_64/lensfun-0.3.2-14.el8.x86_64.rpm.html

Enable PowerTools in our style:
- https://github.com/alvistack/ansible-role-bootstrap/blob/master/vars/centos-8.yml#L42

2020-08-12 08:48 UTC, mccheng7c reviewed
for 3d6f884, This is not related to the dependency issue, I've made some mistake of git rebase.

2020-08-26 08:35 UTC, closed without merging